"""
ORACLE-TMF  ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â·  pipeline/stage_l_report_synthesizer.py
=======================================================
STAGE L ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Forecast Report Synthesizer
Responsibility:
  Consume a fully scored MutationArtifactGraph (all stages A-K complete)
  and emit four independent output artefacts:
      pass
  1. JSON Report   ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â machine-readable, SIEM-ready full analysis dump
  2. YARA Rules    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â proactive detection signatures for future v_{n+1}
  3. STIX 2.1 Bundle ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â TAXII-compatible threat intelligence feed
  4. PDF Brief     ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â human-readable SOC analyst intelligence report
Design philosophy:
  Each output format is generated by its own private method, completely
  independently.  A failure in PDF generation does not prevent YARA or
  STIX output.  Each output is written to an individual file so SOC
  tooling can consume whichever format it understands.
Output schema (ReportBundle dataclass):
  json_path  : str  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â path to the JSON report file
  yara_path  : str  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â path to the .yar YARA rules file
  stix_path  : str  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â path to the STIX 2.1 JSON bundle
  pdf_path   : str  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â path to the PDF intelligence brief
  errors     : dict ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â per-format errors (empty if all succeeded)
Research basis:
  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ YARA rules: https://yara.readthedocs.io/en/stable/writingrules.html
  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ STIX 2.1:   https://docs.oasis-open.org/cti/stix/v2.1/stix-v2.1.html
  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ TAXII 2.1:  https://docs.oasis-open.org/cti/taxii/v2.1/
  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ fpdf2:      https://py-pdf.github.io/fpdf2/
"""
from __future__ import annotations
import json
import logging
import math
import re
import os
import textwrap
import time
from dataclasses import dataclass,field
from datetime import datetime,timezone
from pathlib import Path
from typing import Optional,Any
from config.settings import(
    CONFIDENCE_GATE_THRESHOLD,
    REPORT_OUTPUT_DIR,
    STIX_IDENTITY_CLASS,
    STIX_IDENTITY_NAME,
)
from models.mutation_artifact_graph import MutationArtifactGraph,MutationForecast
from engines.research_readiness import ResearchReadinessEngine
from security import clean_text,redact_secrets
logger=logging.getLogger(__name__)
def _yara_identifier(value:str,max_len:int=80)->str:
    ident=re.sub(r"\W+","_",clean_text(value,max_len)).strip("_")
    if not ident or ident[0].isdigit():
        ident=f"x_{ident}"
    return ident[:max_len]or "UNKNOWN"
def _yara_string(value:str,max_len:int=200)->str:
    """Safely escape a value for use inside a YARA string literal or metadata field.

    Escapes (in order):
      ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ Control characters (\\x00-\\x1f, \\x7f-\\x9f) ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â stripped entirely
      ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ Backslashes  ÃƒÂ¢Ã¢â‚¬Â Ã¢â‚¬â„¢ \\\\
      ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ Double-quotes ÃƒÂ¢Ã¢â‚¬Â Ã¢â‚¬â„¢ \\"
      ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ Newlines (\\n) ÃƒÂ¢Ã¢â‚¬Â Ã¢â‚¬â„¢ \\n  (YARA string literal does not allow bare newlines)
      ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ Carriage returns (\\r) ÃƒÂ¢Ã¢â‚¬Â Ã¢â‚¬â„¢ \\r
      ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ Tabs (\\t) ÃƒÂ¢Ã¢â‚¬Â Ã¢â‚¬â„¢ \\t
    """
    import re as _re
    text=_re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]","",
                   clean_text(redact_secrets(value,max_len),max_len))
    text=text.replace("\\","\\\\")
    text=text.replace('"','\\"')
    text=text.replace("\n","\\n")
    text=text.replace("\r","\\r")
    text=text.replace("\t","\\t")
    return text
@dataclass
class ReportBundle:
    """Paths to all generated report files for a single APK analysis run."""
    json_path:str=""
    yara_path:str=""
    stix_path:str=""
    pdf_path:str=""
    paper_md_path:str=""
    errors:dict=field(default_factory=dict)
class ReportSynthesizer:
    """
    Stage L: Forecast Report Synthesizer.
    The synthesizer is intentionally fault-tolerant: if any single output
    format fails (e.g., fpdf2 not installed), the remaining formats are
    still generated and the error is captured in ReportBundle.errors.
    Usage
    -----
    >>> stage = ReportSynthesizer()
    >>> bundle = stage.run(mag)
    >>> print(bundle.pdf_path)
    """
    STAGE_NAME="STAGE_L"
    _REPORT_TTL_SECONDS:int=int(os.getenv("ORACLE_TMF_REPORT_TTL_SECONDS",str(24*3600)))
    def __init__(self)->None:
        Path(REPORT_OUTPUT_DIR).mkdir(parents=True,exist_ok=True)
        self._purge_stale_reports()
    def _purge_stale_reports(self)->None:
        """V-013: Delete report files older than _REPORT_TTL_SECONDS."""
        import time as _time
        cutoff=_time.time()-self._REPORT_TTL_SECONDS
        report_dir=Path(REPORT_OUTPUT_DIR)
        for f in report_dir.iterdir():
            if f.is_file():
                try:
                    if f.stat().st_mtime<cutoff:
                        f.unlink(missing_ok=True)
                        logger.debug("[Stage L] Purged stale report: %s",f.name)
                except OSError:
                    pass
    def run(self,mag:MutationArtifactGraph,stage2_report:Optional[Any]=None)->ReportBundle:
        """
        Execute Stage L.
        Parameters
        ----------
        mag : MutationArtifactGraph
            Fully scored MAG from Stages A-K.
        Returns
        -------
        ReportBundle
            Paths to each generated output file.
        """
        t0=time.perf_counter()
        logger.info("[Stage L] Starting report synthesis")
        bundle=ReportBundle()
        stem=self._report_stem(mag)
        bundle.json_path=self._safe_generate(
            "json",bundle,lambda:self._generate_json(mag,stem,stage2_report)
        )
        bundle.yara_path=self._safe_generate(
            "yara",bundle,lambda:self._generate_yara(mag,stem)
        )
        bundle.stix_path=self._safe_generate(
            "stix",bundle,lambda:self._generate_stix(mag,stem)
        )
        bundle.pdf_path=self._safe_generate(
            "pdf",bundle,lambda:self._generate_pdf(mag,stem)
        )
        bundle.paper_md_path=self._safe_generate(
            "paper_md",bundle,lambda:self._generate_research_paper_markdown(mag,stem,stage2_report)
        )
        elapsed_ms=(time.perf_counter()-t0)*1000
        logger.info(
            "[Stage L] Complete in %.1f ms | json=%s | yara=%s | stix=%s | pdf=%s",
            elapsed_ms,
            "ÃƒÆ’Ã‚Â¢Ãƒâ€¦Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ"if bundle.json_path else "ÃƒÆ’Ã‚Â¢Ãƒâ€¦Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â",
            "ÃƒÆ’Ã‚Â¢Ãƒâ€¦Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ"if bundle.yara_path else "ÃƒÆ’Ã‚Â¢Ãƒâ€¦Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â",
            "ÃƒÆ’Ã‚Â¢Ãƒâ€¦Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ"if bundle.stix_path else "ÃƒÆ’Ã‚Â¢Ãƒâ€¦Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â",
            "ÃƒÆ’Ã‚Â¢Ãƒâ€¦Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ"if bundle.pdf_path else "ÃƒÆ’Ã‚Â¢Ãƒâ€¦Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â",
        )
        return bundle
    def _generate_json(self,mag:MutationArtifactGraph,stem:str,stage2_report:Optional[Any]=None)->str:
        """
        Generate a SIEM-ready JSON report with the full MAG serialisation
        plus a high-level executive summary section.
        """
        passed=mag.high_confidence_forecasts(CONFIDENCE_GATE_THRESHOLD)
        full_mag=mag.to_dict()
        research_summary=full_mag.get("research_readiness")or{}
        stage2_summary=full_mag.get("stage2_intelligence")or self._stage2_to_dict(stage2_report)
        report={
            "oracle_tmf_version":"1.0.0",
            "report_generated_utc":datetime.now(timezone.utc).isoformat(),
            "research_readiness":research_summary,
            "stage2_summary":stage2_summary,
            "executive_summary":{
                "apk_sha256":mag.apk_metadata.sha256,
                "package_name":mag.apk_metadata.package_name,
                "malware_family":mag.malware_family,
                "family_version":mag.family_version,
                "total_artifacts":mag.total_artifact_count(),
                "artifact_classes":mag.artifact_class_counts(),
                "forecasts_generated":len(mag.forecasts),
                "forecasts_passed_gate":len(passed),
                "highest_confidence":max((f.confidence_score for f in mag.forecasts),default=0.0),
                "predicted_techniques":[f.predicted_technique for f in passed],
            },
            "full_mag":full_mag,
        }
        path=os.path.join(REPORT_OUTPUT_DIR,f"{stem}_report.json")
        with open(path,"w",encoding="utf-8")as fh:
            json.dump(report,fh,indent=2,default=str)
        logger.debug("[Stage L] JSON report written: %s",path)
        return path
    def _generate_yara(self,mag:MutationArtifactGraph,stem:str)->str:
        """
        Generate proactive YARA detection rules for each high-confidence forecast.
        Rule philosophy:
          ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ Strings section uses artifact evidence extracted from the current APK
          ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ These strings are the SCAFFOLDING that will evolve into the next
            active payload ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â detecting them now provides lead-time before the
            threat emerges
          ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ Condition requires ZIP magic (APK = ZIP) + multiple artifact signals
        """
        rules_text=self._yara_file_header(mag)
        passed=mag.high_confidence_forecasts(CONFIDENCE_GATE_THRESHOLD)
        if not passed:
            rules_text+=self._yara_fingerprint_rule(mag)
        else:
            for i,forecast in enumerate(passed,1):
                rules_text+=self._yara_forecast_rule(
                    mag,forecast,rule_index=i)
        path=os.path.join(REPORT_OUTPUT_DIR,f"{stem}_forecast.yar")
        with open(path,"w",encoding="utf-8")as fh:
            fh.write(rules_text)
        logger.debug("[Stage L] YARA rules written: %s (%d rule(s))",
                     path,max(1,len(passed)))
        return path
    def _yara_file_header(self,mag:MutationArtifactGraph)->str:
        """YARA file comment block header."""
        return(
            f"//ORACLE-TMF Proactive YARA Ruleset\n"
            f"//Generated:{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
            f"//APK SHA256:{clean_text(mag.apk_metadata.sha256,80)}\n"
            f"//Package:{clean_text(mag.apk_metadata.package_name,200)}\n"
            f"//Family:{clean_text(mag.malware_family or 'UNKNOWN',120)}\n"
            f"//WARNING:These rules are PROACTIVE forecasts for v_{{n+1}}.\n"
            f"//Deployment before v_{{n+1}}discovery provides temporal advantage.\n"
            f"//Gate threshold applied:C>{CONFIDENCE_GATE_THRESHOLD}\n\n"
        )
    def _yara_forecast_rule(
        self,mag:MutationArtifactGraph,forecast:MutationForecast,rule_index:int
    )->str:
        """Generate one safely escaped YARA rule for a single forecast."""
        family_clean=_yara_identifier(mag.malware_family or "UNKNOWN")
        technique_clean=_yara_identifier(forecast.predicted_technique or "UNKNOWN")
        confidence_pct=int(forecast.confidence_score*100)
        rule_name=f"ORACLE_TMF_{family_clean}_{technique_clean}_Forecast_{confidence_pct:02d}_{rule_index}"
        meta_block=(
            f'    meta:\n'
            f'        oracle_tmf_version="1.0.0"\n'
            f'        description="ORACLE-TMF proactive forecast:{_yara_string(mag.malware_family)}->{_yara_string(forecast.predicted_technique)}({_yara_string(forecast.technique_name)})"\n'
            f'        author="{_yara_string(STIX_IDENTITY_NAME)}"\n'
            f'        date="{datetime.now(timezone.utc).strftime("%Y-%m-%d")}"\n'
            f'        confidence="{forecast.confidence_score:.3f}"\n'
            f'        mitre_tactic="{_yara_string(forecast.predicted_tactic)}"\n'
            f'        mitre_technique="{_yara_string(forecast.predicted_technique)}-{_yara_string(forecast.technique_name)}"\n'
            f'        malware_family="{_yara_string(mag.malware_family)}"\n'
            f'        apk_sha256_analyzed="{_yara_string(mag.apk_metadata.sha256,80)}"\n'
            f'        forecast_status="PROACTIVE_v_n_plus_1"\n'
        )
        if forecast.predicted_target_institutions:
            targets=_yara_string(", ".join(forecast.predicted_target_institutions[:3]))
            meta_block+=f'        predicted_targets="{targets}"\n'
        strings_lines:list[str]=[]
        for i,artifact in enumerate(mag.dead_code[:3],1):
            token=_yara_string(artifact.method_name.split("(")[0],40).strip()
            if token and len(token)>4:
                strings_lines.append(f'        $dead_code_{i}="{token}" ascii nocase')
        for i,stub in enumerate(mag.c2_stubs[:2],1):
            if stub.extracted_url:
                strings_lines.append(f'        $c2_stub_{i}="{_yara_string(stub.extracted_url,60)}" ascii')
            if stub.framework:
                strings_lines.append(f'        $c2_framework_{i}="{_yara_string(stub.framework,80)}" ascii')
        for i,perm in enumerate(mag.unused_permissions[:2],1):
            strings_lines.append(f'        $unused_perm_{i}="{_yara_string(perm.permission_name,120)}" ascii')
        for i,ps in enumerate(sorted(mag.placeholder_strings,key=lambda x:x.entropy,reverse=True)[:2],1):
            if ps.entropy>4.5 and len(ps.value)<80:
                strings_lines.append(f'        $placeholder_{i}="{_yara_string(ps.value,60)}" ascii')
        if not strings_lines:
            family_marker=_yara_string(mag.malware_family or "UNKNOWN",80)
            strings_lines.append(f'        $family_marker="{family_marker}" ascii nocase')
        strings_block="    strings:\n"+"\n".join(strings_lines)+"\n"
        condition_block=(
            f"    condition:\n"
            f"        uint16(0)==0x6B50 and//APK/ZIP magic bytes\n"
            f"        filesize<100MB and\n"
            f"(\n"
            f"            2 of($dead_code_*)or\n"
            f"(1 of($c2_stub_*)and 1 of($unused_perm_*))\n"
            f")\n"
        )
        return f"rule{rule_name}\n{{\n{meta_block}{strings_block}{condition_block}}}\n\n"
    def _yara_fingerprint_rule(self,mag:MutationArtifactGraph)->str:
        """Generic APK fingerprint rule when no forecast passes the gate."""
        family_clean=_yara_identifier(mag.malware_family or "UNKNOWN")
        rule_name=f"ORACLE_TMF_{family_clean}_APK_Fingerprint"
        return(
            f"rule{rule_name}\n"
            f"{{\n"
            f"    meta:\n"
            f'        description="ORACLE-TMF APK fingerprint-no high-confidence forecast"\n'
            f'        apk_sha256="{_yara_string(mag.apk_metadata.sha256,80)}"\n'
            f'        package="{_yara_string(mag.apk_metadata.package_name)}"\n'
            f"    condition:\n"
            f'        uint16(0)==0x6B50 and\n'
            f'        hash.sha256(0,filesize)=="{_yara_string(mag.apk_metadata.sha256,80)}"\n'
            f"}}\n\n"
        )
    def _generate_stix(self,mag:MutationArtifactGraph,stem:str)->str:
        """
        Generate a STIX 2.1 bundle containing:
          ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ Identity  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ORACLE-TMF as the intelligence producer
          ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ Malware   ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â the analysed malware family
          ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ Indicators ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â one per passing forecast (proactive detection pattern)
          ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ AttackPatterns ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â MITRE ATT&CK technique references
          ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ Relationships ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Indicator ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ indicates ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ Malware
                           Malware ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ uses ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ AttackPattern
        The bundle is TAXII-compatible and can be submitted directly to a
        TAXII 2.1 collection endpoint.
        """
        try:
            import stix2
        except ImportError:
            raise ImportError(
                "stix2 not installed. Install it inside the project virtualenv: python -m pip install stix2"
            )
        now=datetime.now(timezone.utc)
        stix_objects:list=[]
        identity=stix2.Identity(
            name=STIX_IDENTITY_NAME,
            identity_class=STIX_IDENTITY_CLASS,
            description=(
                "ORACLE-TMF: Observational Reasoning and Coercive Analysis for "
                "Latent Evolution ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Temporal Mutation Forecaster. "
                "Automated proactive threat intelligence platform."
            ),
        )
        stix_objects.append(identity)
        family_name=mag.malware_family or mag.apk_metadata.package_name or "UnknownMalware"
        malware=stix2.Malware(
            name=family_name,
            is_family=True,
            malware_types=["banking-trojan"],
            description=(
                f"Android banking trojan identified from APK "
                f"{mag.apk_metadata.sha256[:16]}..."
                f"Package:{mag.apk_metadata.package_name}"
            ),
            created_by_ref=identity.id,
            first_seen=now,
        )
        stix_objects.append(malware)
        passed=mag.high_confidence_forecasts(CONFIDENCE_GATE_THRESHOLD)
        for forecast in passed:
            attack_pattern=stix2.AttackPattern(
                name=f"{forecast.predicted_technique}-{forecast.technique_name}",
                description=(
                    f"MITRE ATT&CK for Mobile:{forecast.predicted_tactic}/"
                    f"{forecast.predicted_technique}"
                ),
                created_by_ref=identity.id,
                external_references=[
                    stix2.ExternalReference(
                        source_name="MITRE ATT&CK for Mobile",
                        url=f"https://attack.mitre.org/techniques/{forecast.predicted_technique.replace('.','/')}/",
                        external_id=forecast.predicted_technique,
                    )
                ],
            )
            stix_objects.append(attack_pattern)
            sha256_hash=mag.apk_metadata.sha256
            stix_pattern=f"[file:hashes.'SHA-256'='{sha256_hash}']"if sha256_hash else(
                f"[software:name='{family_name}']"
            )
            indicator=stix2.Indicator(
                name=f"ORACLE-TMF Forecast:{forecast.predicted_technique}",
                description=(
                    f"PROACTIVE FORECAST(confidence={forecast.confidence_score:.3f}):"
                    f"The analysed{family_name}APK contains mutation artifacts that predict "
                    f"implementation of{forecast.predicted_technique}({forecast.technique_name})"
                    f"in the next release.Model summary:{clean_text(redact_secrets(forecast.rationale,400),400)}"
                ),
                pattern=stix_pattern,
                pattern_type="stix",
                valid_from=now,
                indicator_types=["malicious-activity"],
                confidence=int(forecast.confidence_score*100),
                created_by_ref=identity.id,
                labels=["oracle-tmf-proactive-forecast"],
            )
            stix_objects.append(indicator)
            rel_indicates=stix2.Relationship(
                relationship_type="indicates",
                source_ref=indicator.id,
                target_ref=malware.id,
                created_by_ref=identity.id,
                description=f"Mutation artifacts in this APK indicate future{family_name}capability",
            )
            stix_objects.append(rel_indicates)
            rel_uses=stix2.Relationship(
                relationship_type="uses",
                source_ref=malware.id,
                target_ref=attack_pattern.id,
                created_by_ref=identity.id,
                description=f"ORACLE-TMF predicts{family_name}will use this technique in v_{{n+1}}",
            )
            stix_objects.append(rel_uses)
        bundle=stix2.Bundle(objects=stix_objects,allow_custom=True)
        path=os.path.join(REPORT_OUTPUT_DIR,f"{stem}_stix_bundle.json")
        with open(path,"w",encoding="utf-8")as fh:
            fh.write(bundle.serialize(pretty=True))
        logger.debug(
            "[Stage L] STIX 2.1 bundle written: %s (%d objects)",path,len(stix_objects))
        return path
    @staticmethod
    def _stage2_to_dict(stage2_report:Optional[Any])->dict:
        """Return the compact Stage 2 summary used by reports and exports."""
        if stage2_report is None:
            return{}
        try:
            summary=ResearchReadinessEngine.summarize_stage2(stage2_report)
            return dict(summary.__dict__)
        except Exception:
            to_dict=getattr(stage2_report,"to_dict",None)
            if callable(to_dict):
                try:
                    return to_dict()
                except Exception:
                    return{}
        return{}
    @staticmethod
    def _md_cell(value,max_len:int=240)->str:
        """Escape untrusted values for a Markdown table cell."""
        text=clean_text(redact_secrets(str(value),max_len),max_len)
        return text.replace("|","\\|").replace("\r\n","<br>").replace("\n","<br>")
    @staticmethod
    def _score_text(value)->str:
        try:
            return f"{float(value):.3f}"
        except(TypeError,ValueError):
            return "0.000"
    def _generate_research_paper_markdown(
        self,
        mag:MutationArtifactGraph,
        stem:str,
        stage2_report:Optional[Any]=None,
    )->str:
        """
        Generate a publication-oriented Markdown paper draft.

        This is intentionally a draft, not a final claim of peer review. It
        packages methods, evidence, limitations, reproducibility, and suggested
        figures so analysts can move from one APK run to a defensible paper.
        """
        full_mag=mag.to_dict()
        rr=full_mag.get("research_readiness")or{}
        stage2=full_mag.get("stage2_intelligence")or self._stage2_to_dict(stage2_report)
        passed=mag.high_confidence_forecasts(CONFIDENCE_GATE_THRESHOLD)
        family=self._md_cell(mag.malware_family or mag.apk_metadata.package_name or "Unknown family")
        package=self._md_cell(mag.apk_metadata.package_name or "unknown")
        sha256=self._md_cell(mag.apk_metadata.sha256 or "unknown",80)
        generated=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        headline=rr.get("headline_claim")or(
            f"ORACLE-TMF analyzed{family}and extracted{mag.total_artifact_count()}mutation artifacts."
        )
        lines:list[str]=[
            f"# ORACLE-TMF Case Study:{family}",
            "",
            "## Abstract",
            "",
            self._md_cell(headline,900),
            "",
            "This draft was generated automatically from the ORACLE-TMF Mutation Artifact Graph. It should be reviewed by a human analyst before submission or publication.",
            "",
            "## Sample Card",
            "",
            "| Field | Value |",
            "| --- | --- |",
            f"|Package|{package}|",
            f"|SHA-256|`{sha256}`|",
            f"|Family|{family}|",
            f"|Version|{self._md_cell(mag.apk_metadata.version_name or 'unknown')}/code{mag.apk_metadata.version_code}|",
            f"|File size|{mag.apk_metadata.file_size_bytes}bytes|",
            f"|Generated|{generated}|",
            "",
            "## Research Readiness Metrics",
            "",
            "| Metric | Score |",
            "| --- | ---: |",
            f"|Publication readiness|{self._score_text(rr.get('publication_readiness_score'))}|",
            f"|Evidence strength|{self._score_text(rr.get('evidence_strength_score'))}|",
            f"|Novelty|{self._score_text(rr.get('novelty_score'))}|",
            f"|Reproducibility|{self._score_text(rr.get('reproducibility_score'))}|",
            f"|Stage 2 intelligence|{self._score_text(rr.get('stage2_intelligence_score'))}|",
            f"|Operational risk|{self._score_text(rr.get('operational_risk_score'))}|",
            "",
            f"**Paper readiness:**{self._md_cell(rr.get('paper_readiness','INSUFFICIENT'))}",
            f"**Risk tier:**{self._md_cell(rr.get('risk_tier','LOW'))}",
            "",
            "## Methodology",
            "",
        ]
        for card in rr.get("methodology_cards",[]):
            lines.append(f"-**{self._md_cell(card.get('method'))}**:{self._md_cell(card.get('purpose'),500)}Status:`{self._md_cell(card.get('status'))}`.")
        if not rr.get("methodology_cards"):
            lines.append("- Static APK analysis, mutation-artifact extraction, and report synthesis were executed with available pipeline stages.")
        lines.extend([
            "",
            "## Evidence Matrix",
            "",
            "| Artifact class | Count | Stage | Strength | Interpretation |",
            "| --- | ---: | --- | --- | --- |",
        ])
        for row in rr.get("evidence_matrix",[]):
            lines.append(
                "| "
                f"{self._md_cell(row.get('artifact_class'))}|"
                f"{int(row.get('count',0))}|"
                f"{self._md_cell(row.get('stage'))}|"
                f"{self._md_cell(row.get('strength'))}|"
                f"{self._md_cell(row.get('interpretation'),500)}|"
            )
        lines.extend([
            "",
            "## Stage 1 Forecast Results",
            "",
            "| Technique | Name | Confidence | Gate | Supporting artifacts |",
            "| --- | --- | ---: | --- | --- |",
        ])
        if mag.forecasts:
            for forecast in mag.forecasts:
                support=", ".join(forecast.supporting_artifacts)or "none recorded"
                lines.append(
                    "| "
                    f"{self._md_cell(forecast.predicted_technique)}|"
                    f"{self._md_cell(forecast.technique_name)}|"
                    f"{forecast.confidence_score:.3f}|"
                    f"{'pass' if forecast.passes_gate else 'hold'}|"
                    f"{self._md_cell(support,400)}|"
                )
        else:
            lines.append("| No forecasts generated | - | 0.000 | hold | Stage J/K unavailable or skipped |")
        lines.extend(["","## Stage 2 Intelligence Summary",""])
        if stage2 and stage2.get("available",True):
            enabled=", ".join(stage2.get("enabled_stages",[]))or "none recorded"
            threat=stage2.get("highest_network_threat",stage2.get("highest_ddos_threat","NONE"))
            lines.extend([
                "| Signal | Value |",
                "| --- | --- |",
                f"|Enabled stages|{self._md_cell(enabled,500)}|",
                f"|Safety mode|{self._md_cell(stage2.get('safety_mode','SAFE_STATIC_DEFAULT'))}|",
                f"|NAV redirection|{self._md_cell(stage2.get('nav_redirection','none'))}|",
                f"|Builder cluster|{self._md_cell(stage2.get('builder_cluster_id',-1))}|",
                f"|MIRAGE robustness|{self._score_text(stage2.get('robustness_score'))}|",
                f"|Highest network threat|{self._md_cell(threat)}|",
                f"|Network threat count|{self._md_cell(stage2.get('network_threat_count',0))}|",
                f"|Suricata rules|{self._md_cell(stage2.get('suricata_rules_count',0))}|",
                f"|STIX indicators|{self._md_cell(stage2.get('stix_indicators_count',0))}|",
                f"|DGA profile detected|{'yes' if stage2.get('has_dga')else 'no'}|",
                f"|Collusion paths|{self._md_cell(stage2.get('collusion_paths_found',0))}|",
            ])
        else:
            lines.append("Stage 2 intelligence was not available for this run.")
        lines.extend(["","## Key Findings",""])
        for item in rr.get("key_findings",[]):
            lines.append(f"-{self._md_cell(item,700)}")
        lines.extend(["","## Threats to Validity",""])
        for item in rr.get("limitations",[]):
            lines.append(f"-{self._md_cell(item,700)}")
        lines.extend(["","## Reproducibility Checklist","","| Item | Passed |","| --- | --- |"])
        for item in rr.get("reproducibility_checklist",[]):
            lines.append(f"|{self._md_cell(item.get('item'))}|{'yes' if item.get('passed')else 'no'}|")
        lines.extend(["","## Suggested Figures and Tables",""])
        for item in rr.get("suggested_figures",[]):
            lines.append(f"-{self._md_cell(item,400)}")
        lines.extend(["","## Recommended Next Steps",""])
        for item in rr.get("recommended_next_steps",[]):
            lines.append(f"-{self._md_cell(item,700)}")
        lines.extend([
            "",
            "## Ethics and Safety Statement",
            "",
            "This report is for defensive malware analysis, detection engineering, and academic study. It does not contain instructions for weaponization or deployment of malicious capabilities.",
            "",
        ])
        path=os.path.join(REPORT_OUTPUT_DIR,f"{stem}_research_paper.md")
        with open(path,"w",encoding="utf-8")as fh:
            fh.write("\n".join(lines).rstrip()+"\n")
        logger.debug("[Stage L] Research paper draft written: %s",path)
        return path
    def _generate_pdf(self,mag:MutationArtifactGraph,stem:str)->str:
        """
        Generate a human-readable PDF intelligence brief for SOC analysts.
        Structure:
          Page 1  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Cover / Executive Summary
          Page 2  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â APK Metadata + Artifact Inventory Table
          Page 3+ ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Per-forecast detail pages (one per passing forecast)
          Final   ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Appendix: Stage errors and pipeline timings
        """
        try:
            from fpdf import FPDF
        except ImportError:
            raise ImportError(
                "fpdf2 not installed. Install it inside the project virtualenv: python -m pip install fpdf2"
            )
        class TMFReport(FPDF):
            """Custom FPDF subclass for ORACLE-TMF branded reports."""
            BRAND_DARK=(15,15,30)
            BRAND_CYAN=(0,245,255)
            BRAND_GREEN=(0,255,100)
            BRAND_WHITE=(240,240,240)
            BRAND_GREY=(100,100,120)
            def header(self):
                self.set_fill_color(*self.BRAND_DARK)
                self.rect(0,0,210,14,"F")
                self.set_font("Helvetica","B",8)
                self.set_text_color(*self.BRAND_CYAN)
                self.set_y(4)
                self.cell(
                    0,6,"ORACLE-TMF  ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â·  PROACTIVE THREAT INTELLIGENCE BRIEF  ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â·  CONFIDENTIAL",align="C")
                self.ln(10)
            def footer(self):
                self.set_y(-12)
                self.set_font("Helvetica","",7)
                self.set_text_color(*self.BRAND_GREY)
                self.cell(
                    0,5,f"Generated{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â·  Page{self.page_no()}",align="C")
            def section_title(self,title:str)->None:
                self.set_fill_color(*self.BRAND_DARK)
                self.set_text_color(*self.BRAND_CYAN)
                self.set_font("Helvetica","B",11)
                self.cell(0,8,f"{title}",fill=True,ln=True)
                self.ln(2)
            def key_value_row(self,key:str,value:str)->None:
                self.set_font("Helvetica","B",9)
                self.set_text_color(*self.BRAND_GREY)
                self.cell(55,6,key+":",ln=False)
                self.set_font("Helvetica","",9)
                self.set_text_color(*self.BRAND_WHITE)
                self.multi_cell(0,6,value[:120])
            def confidence_bar(self,score:float,label:str)->None:
                """Draw a visual confidence bar."""
                bar_w=130
                filled=int(bar_w*score)
                self.set_fill_color(40,40,60)
                self.rect(self.get_x(),self.get_y(),bar_w,6,"F")
                color=(0,255,100)if score>0.8 else(
                    255,200,0)if score>0.6 else(255,80,80)
                self.set_fill_color(*color)
                self.rect(self.get_x(),self.get_y(),filled,6,"F")
                self.set_font("Helvetica","B",8)
                self.set_text_color(255,255,255)
                x_after=self.get_x()+bar_w+4
                self.set_xy(x_after,self.get_y())
                self.cell(50,6,f"{label}({score:.3f})")
                self.ln(8)
        pdf=TMFReport()
        pdf.set_fill_color(15,15,30)
        pdf.set_auto_page_break(auto=True,margin=15)
        pdf.set_margins(12,16,12)
        pdf.add_page()
        pdf.set_fill_color(15,15,30)
        pdf.rect(0,0,210,297,"F")
        pdf.set_font("Helvetica","B",22)
        pdf.set_text_color(0,245,255)
        pdf.set_y(30)
        pdf.cell(0,12,"ORACLE-TMF",align="C",ln=True)
        pdf.set_font("Helvetica","",13)
        pdf.set_text_color(200,200,220)
        pdf.cell(0,8,"Proactive Mutation Intelligence Brief",
                 align="C",ln=True)
        pdf.ln(4)
        pdf.set_draw_color(0,245,255)
        pdf.set_line_width(0.8)
        pdf.line(30,pdf.get_y(),180,pdf.get_y())
        pdf.ln(6)
        pdf.set_font("Helvetica","B",10)
        pdf.set_text_color(0,245,255)
        pdf.cell(
            0,7,f"Target:{mag.malware_family or 'UNKNOWN FAMILY'}",align="C",ln=True)
        pdf.set_font("Helvetica","",9)
        pdf.set_text_color(180,180,200)
        sha_display=mag.apk_metadata.sha256[:32]+\
            "..."if mag.apk_metadata.sha256 else "N/A"
        pdf.cell(0,6,f"SHA256:{sha_display}",align="C",ln=True)
        pdf.cell(
            0,6,f"Package:{mag.apk_metadata.package_name or 'N/A'}",align="C",ln=True)
        pdf.ln(8)
        passed=mag.high_confidence_forecasts(CONFIDENCE_GATE_THRESHOLD)
        pdf.set_font("Helvetica","B",14)
        pdf.set_text_color(0,255,100)
        pdf.cell(
            0,10,f"{len(passed)}High-Confidence Forecast(s)Generated",align="C",ln=True)
        pdf.ln(4)
        if passed:
            pdf.set_font("Helvetica","",9)
            pdf.set_text_color(200,200,220)
            for f in passed[:3]:
                pdf.cell(
                    0,6,f"ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢{f.predicted_technique}({f.technique_name})",align="C",ln=True)
        pdf.ln(8)
        counts=mag.artifact_class_counts()
        pdf.set_font("Helvetica","B",9)
        pdf.set_text_color(0,245,255)
        pdf.cell(0,7,"Artifact Inventory",align="C",ln=True)
        pdf.set_font("Helvetica","",8)
        pdf.set_text_color(180,180,200)
        for cls,count in counts.items():
            if count>0:
                cls_display=cls.replace("CLASS_","").replace("_"," ")
                pdf.cell(0,5,f"{cls_display}:{count}",align="C",ln=True)
        pdf.add_page()
        pdf.set_fill_color(15,15,30)
        pdf.rect(0,0,210,297,"F")
        pdf.section_title("APK Metadata")
        meta=mag.apk_metadata
        fields=[
            ("SHA-256",meta.sha256 or "N/A"),
            ("MD5",meta.md5 or "N/A"),
            ("Package",meta.package_name or "N/A"),
            ("Version",f"{meta.version_name}(code{meta.version_code})"),
            ("Size",f"{meta.file_size_bytes/1024:.1f}KB"),
            ("Min SDK",str(meta.min_sdk)),
            ("Target SDK",str(meta.target_sdk)),
            ("Cert Issuer",meta.cert_issuer[:80]or "N/A"),
            ("Packed","YES ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â "+meta.packer_hint if meta.is_packed else "No"),
            ("Family",mag.malware_family or "Unidentified"),
            ("Family Ver.",mag.family_version or "Unknown"),
        ]
        for k,v in fields:
            pdf.key_value_row(k,v)
        pdf.ln(6)
        pdf.section_title("7-Class Mutation Artifact Inventory")
        col_widths=[90,30,30,36]
        headers=["Artifact Class","Count","Gate","Risk"]
        pdf.set_font("Helvetica","B",9)
        pdf.set_text_color(0,245,255)
        pdf.set_fill_color(20,20,40)
        for h,w in zip(headers,col_widths):
            pdf.cell(w,7,h,border=1,fill=True)
        pdf.ln()
        row_data=[
            ("CLASS 1 ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Dead Code / Unreachable Methods",
             len(mag.dead_code),"ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ DTE","HIGH"),
            ("CLASS 2 ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Unused Permission Intents",len(
                mag.unused_permissions),"ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ Stage J","HIGH"),
            ("CLASS 3 ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Placeholder Strings & Resources",len(
                mag.placeholder_strings),"ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ Stage J","MEDIUM"),
            ("CLASS 4 ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â C2 Endpoint Stubs",len(
                mag.c2_stubs),"ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ Stage J","CRITICAL"),
            ("CLASS 5 ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Partial API Implementations",
             len(mag.partial_apis),"ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ DTE","HIGH"),
            ("CLASS 6 ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Unfinished UI Flows",len(
                mag.unfinished_ui_flows),"ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ Stage J","MEDIUM"),
            ("CLASS 7 ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â GenAI API Scaffolds (TMF-Psi)",
             len(mag.genai_scaffolds),"ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ Stage J","CRITICAL"),
        ]
        pdf.set_font("Helvetica","",8)
        for row in row_data:
            cls_name,count,gate,risk=row
            risk_colors={"CRITICAL":(255,60,60),"HIGH":(
                255,160,0),"MEDIUM":(200,200,0)}
            pdf.set_text_color(200,200,220)
            pdf.cell(col_widths[0],6,cls_name[:55],border=1)
            pdf.cell(col_widths[1],6,str(count),border=1,align="C")
            pdf.cell(col_widths[2],6,gate,border=1,align="C")
            pdf.set_text_color(*risk_colors.get(risk,(200,200,200)))
            pdf.cell(col_widths[3],6,risk,border=1,align="C")
            pdf.ln()
            pdf.set_text_color(200,200,220)
        for i,forecast in enumerate(passed,1):
            pdf.add_page()
            pdf.set_fill_color(15,15,30)
            pdf.rect(0,0,210,297,"F")
            pdf.section_title(f"Forecast #{i}:{forecast.predicted_technique}")
            pdf.set_text_color(0,245,255)
            pdf.set_font("Helvetica","B",9)
            pdf.cell(0,6,"Bayesian Confidence Score",ln=True)
            pdf.confidence_bar(forecast.confidence_score,"C")
            pdf.ln(2)
            pdf.key_value_row("MITRE Tactic",forecast.predicted_tactic)
            pdf.key_value_row(
                "MITRE Technique",f"{forecast.predicted_technique}ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â{forecast.technique_name}")
            pdf.key_value_row(
                "P_LLM",f"{forecast.p_llm:.3f}(Skeptical Validator)")
            pdf.key_value_row(
                "D_artifact ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â MVV",f"{forecast.artifact_density:.3f}ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â{forecast.mvv_normalized:.3f}={forecast.artifact_density*forecast.mvv_normalized:.3f}")
            pdf.key_value_row(
                "H_prior",f"{forecast.h_prior:.3f}(Historical family frequency)")
            pdf.ln(3)
            pdf.section_title("Supporting Artifact Classes")
            pdf.set_font("Helvetica","",9)
            pdf.set_text_color(180,200,180)
            for cls in forecast.supporting_artifacts:
                pdf.cell(0,6,f"  ÃƒÆ’Ã‚Â¢Ãƒâ€¦Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ{cls}",ln=True)
            pdf.ln(3)
            if forecast.predicted_target_institutions:
                pdf.section_title("Targeting Intelligence")
                pdf.set_font("Helvetica","",9)
                pdf.set_text_color(255,160,0)
                pdf.cell(0,6,"Predicted Target Institutions:",ln=True)
                pdf.set_text_color(200,200,220)
                for inst in forecast.predicted_target_institutions:
                    pdf.cell(0,5,f"  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢{inst}",ln=True)
                if forecast.predicted_target_countries:
                    pdf.set_text_color(255,160,0)
                    pdf.cell(0,6,"Predicted Target Regions:",ln=True)
                    pdf.set_text_color(200,200,220)
                    for country in forecast.predicted_target_countries:
                        pdf.cell(0,5,f"  ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢{country}",ln=True)
                pdf.ln(3)
            pdf.section_title("Model Evidence Summary")
            pdf.set_font("Helvetica","",8)
            pdf.set_text_color(190,190,210)
            wrapped=textwrap.fill(clean_text(redact_secrets(forecast.rationale,800),800),width=100)
            for line in wrapped.splitlines():
                pdf.cell(0,5,line[:100],ln=True)
        if mag.stage_errors or mag.stage_timings_ms:
            pdf.add_page()
            pdf.set_fill_color(15,15,30)
            pdf.rect(0,0,210,297,"F")
            pdf.section_title("Appendix ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â Pipeline Diagnostics")
            pdf.set_font("Helvetica","B",9)
            pdf.set_text_color(0,245,255)
            pdf.cell(0,7,"Stage Timings",ln=True)
            pdf.set_font("Helvetica","",8)
            pdf.set_text_color(180,180,200)
            for stage,ms in sorted(mag.stage_timings_ms.items()):
                pdf.cell(0,5,f"{stage:<20}{ms:.1f}ms",ln=True)
            if mag.stage_errors:
                pdf.ln(4)
                pdf.set_font("Helvetica","B",9)
                pdf.set_text_color(255,80,80)
                pdf.cell(0,7,"Stage Errors",ln=True)
                pdf.set_font("Helvetica","",8)
                for stage,err in mag.stage_errors.items():
                    pdf.cell(0,5,f"{stage}:{str(err)[:80]}",ln=True)
        path=os.path.join(REPORT_OUTPUT_DIR,
                            f"{stem}_intelligence_brief.pdf")
        pdf.output(path)
        logger.debug(
            "[Stage L] PDF brief written: %s (%d pages)",path,pdf.page)
        return path
    def _safe_generate(self,format_name:str,bundle:ReportBundle,generator_fn)->str:
        """
        Execute a report generator function, capturing any exception into
        bundle.errors rather than propagating it.  Returns the output path
        or empty string on failure.
        """
        try:
            return generator_fn()
        except Exception as exc:
            logger.warning("[Stage L] %s generation failed: %s",
                           format_name.upper(),exc)
            bundle.errors[format_name]=str(exc)
            return ""
    @staticmethod
    def _report_stem(mag:MutationArtifactGraph)->str:
        """Generate a filesystem-safe stem for report file names."""
        import re
        sha_prefix=mag.apk_metadata.sha256[:
                                             12]if mag.apk_metadata.sha256 else "unknown"
        family_part=re.sub(r"\W+","_",mag.malware_family or "unknown")
        ts=datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        return f"{family_part}_{sha_prefix}_{ts}"
