"""
ORACLE-TMF  ·  pipeline/stage_l_report_synthesizer.py
=======================================================
STAGE L — Forecast Report Synthesizer

Responsibility:
  Consume a fully scored MutationArtifactGraph (all stages A-K complete)
  and emit four independent output artefacts:

  1. JSON Report   — machine-readable, SIEM-ready full analysis dump
  2. YARA Rules    — proactive detection signatures for future v_{n+1}
  3. STIX 2.1 Bundle — TAXII-compatible threat intelligence feed
  4. PDF Brief     — human-readable SOC analyst intelligence report

Design philosophy:
  Each output format is generated by its own private method, completely
  independently.  A failure in PDF generation does not prevent YARA or
  STIX output.  Each output is written to an individual file so SOC
  tooling can consume whichever format it understands.

Output schema (ReportBundle dataclass):
  json_path  : str  — path to the JSON report file
  yara_path  : str  — path to the .yar YARA rules file
  stix_path  : str  — path to the STIX 2.1 JSON bundle
  pdf_path   : str  — path to the PDF intelligence brief
  errors     : dict — per-format errors (empty if all succeeded)

Research basis:
  • YARA rules: https://yara.readthedocs.io/en/stable/writingrules.html
  • STIX 2.1:   https://docs.oasis-open.org/cti/stix/v2.1/stix-v2.1.html
  • TAXII 2.1:  https://docs.oasis-open.org/cti/taxii/v2.1/
  • fpdf2:      https://py-pdf.github.io/fpdf2/
"""

from __future__ import annotations

import json
import logging
import math
import os
import textwrap
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from config.settings import (
    CONFIDENCE_GATE_THRESHOLD,
    REPORT_OUTPUT_DIR,
    STIX_IDENTITY_CLASS,
    STIX_IDENTITY_NAME,
)
from models.mutation_artifact_graph import MutationArtifactGraph, MutationForecast

logger = logging.getLogger(__name__)


@dataclass
class ReportBundle:
    """Paths to all generated report files for a single APK analysis run."""
    json_path: str = ""
    yara_path: str = ""
    stix_path: str = ""
    pdf_path:  str = ""
    errors:    dict = field(default_factory=dict)


class ReportSynthesizer:
    """
    Stage L: Forecast Report Synthesizer.

    The synthesizer is intentionally fault-tolerant: if any single output
    format fails (e.g., fpdf2 not installed), the remaining formats are
    still generated and the error is captured in ReportBundle.errors.

    Usage
    -----
    >>> stage = ReportSynthesizer()
    >>> bundle = stage.run(mag)
    >>> print(bundle.pdf_path)
    """

    STAGE_NAME = "STAGE_L"

    def __init__(self) -> None:
        Path(REPORT_OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

    # ─────────────────────────────────────────────────────────
    #  PUBLIC API
    # ─────────────────────────────────────────────────────────

    def run(self, mag: MutationArtifactGraph) -> ReportBundle:
        """
        Execute Stage L.

        Parameters
        ----------
        mag : MutationArtifactGraph
            Fully scored MAG from Stages A-K.

        Returns
        -------
        ReportBundle
            Paths to each generated output file.
        """
        t0 = time.perf_counter()
        logger.info("[Stage L] Starting report synthesis")

        bundle = ReportBundle()
        stem = self._report_stem(mag)

        # ── 1. JSON report (always attempted first — baseline output) ──
        bundle.json_path = self._safe_generate(
            "json", bundle, lambda: self._generate_json(mag, stem)
        )

        # ── 2. YARA rules ──────────────────────────────────────────────
        bundle.yara_path = self._safe_generate(
            "yara", bundle, lambda: self._generate_yara(mag, stem)
        )

        # ── 3. STIX 2.1 bundle ────────────────────────────────────────
        bundle.stix_path = self._safe_generate(
            "stix", bundle, lambda: self._generate_stix(mag, stem)
        )

        # ── 4. PDF intelligence brief ─────────────────────────────────
        bundle.pdf_path = self._safe_generate(
            "pdf", bundle, lambda: self._generate_pdf(mag, stem)
        )

        elapsed_ms = (time.perf_counter() - t0) * 1000
        logger.info(
            "[Stage L] Complete in %.1f ms | json=%s | yara=%s | stix=%s | pdf=%s",
            elapsed_ms,
            "✓" if bundle.json_path else "✗",
            "✓" if bundle.yara_path else "✗",
            "✓" if bundle.stix_path else "✗",
            "✓" if bundle.pdf_path  else "✗",
        )
        return bundle

    # ─────────────────────────────────────────────────────────
    #  OUTPUT 1 — JSON REPORT
    # ─────────────────────────────────────────────────────────

    def _generate_json(self, mag: MutationArtifactGraph, stem: str) -> str:
        """
        Generate a SIEM-ready JSON report with the full MAG serialisation
        plus a high-level executive summary section.
        """
        passed = mag.high_confidence_forecasts(CONFIDENCE_GATE_THRESHOLD)
        report = {
            "oracle_tmf_version":   "1.0.0",
            "report_generated_utc": datetime.now(timezone.utc).isoformat(),
            "executive_summary": {
                "apk_sha256":          mag.apk_metadata.sha256,
                "package_name":        mag.apk_metadata.package_name,
                "malware_family":      mag.malware_family,
                "family_version":      mag.family_version,
                "total_artifacts":     mag.total_artifact_count(),
                "artifact_classes":    mag.artifact_class_counts(),
                "forecasts_generated": len(mag.forecasts),
                "forecasts_passed_gate": len(passed),
                "highest_confidence":  max((f.confidence_score for f in mag.forecasts), default=0.0),
                "predicted_techniques": [f.predicted_technique for f in passed],
            },
            "full_mag": mag.to_dict(),
        }
        path = os.path.join(REPORT_OUTPUT_DIR, f"{stem}_report.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(report, fh, indent=2, default=str)
        logger.debug("[Stage L] JSON report written: %s", path)
        return path

    # ─────────────────────────────────────────────────────────
    #  OUTPUT 2 — YARA RULES
    # ─────────────────────────────────────────────────────────

    def _generate_yara(self, mag: MutationArtifactGraph, stem: str) -> str:
        """
        Generate proactive YARA detection rules for each high-confidence forecast.

        Rule philosophy:
          • Strings section uses artifact evidence extracted from the current APK
          • These strings are the SCAFFOLDING that will evolve into the next
            active payload — detecting them now provides lead-time before the
            threat emerges
          • Condition requires ZIP magic (APK = ZIP) + multiple artifact signals
        """
        rules_text = self._yara_file_header(mag)
        passed = mag.high_confidence_forecasts(CONFIDENCE_GATE_THRESHOLD)

        if not passed:
            # No forecasts passed the gate — generate a generic fingerprint rule
            rules_text += self._yara_fingerprint_rule(mag)
        else:
            for i, forecast in enumerate(passed, 1):
                rules_text += self._yara_forecast_rule(mag, forecast, rule_index=i)

        path = os.path.join(REPORT_OUTPUT_DIR, f"{stem}_forecast.yar")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(rules_text)
        logger.debug("[Stage L] YARA rules written: %s (%d rule(s))", path, max(1, len(passed)))
        return path

    def _yara_file_header(self, mag: MutationArtifactGraph) -> str:
        """YARA file comment block header."""
        return (
            f"// ORACLE-TMF Proactive YARA Ruleset\n"
            f"// Generated : {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
            f"// APK SHA256: {mag.apk_metadata.sha256}\n"
            f"// Package   : {mag.apk_metadata.package_name}\n"
            f"// Family    : {mag.malware_family or 'UNKNOWN'}\n"
            f"// WARNING   : These rules are PROACTIVE forecasts for v_{{n+1}}.\n"
            f"//             Deployment before v_{{n+1}} discovery provides temporal advantage.\n"
            f"//             Gate threshold applied: C > {CONFIDENCE_GATE_THRESHOLD}\n\n"
        )

    def _yara_forecast_rule(
        self, mag: MutationArtifactGraph, forecast: MutationForecast, rule_index: int
    ) -> str:
        """Generate one YARA rule for a single passing forecast."""
        # Sanitise rule name (YARA identifiers: alphanumeric + underscore)
        import re
        family_clean    = re.sub(r"\W+", "_", mag.malware_family or "UNKNOWN")
        technique_clean = re.sub(r"\W+", "_", forecast.predicted_technique or "UNKNOWN")
        confidence_pct  = int(forecast.confidence_score * 100)

        rule_name = f"ORACLE_TMF_{family_clean}_{technique_clean}_Forecast_{confidence_pct:02d}_{rule_index}"

        # ── META ────────────────────────────────────────────────────────
        meta_block = (
            f'    meta:\n'
            f'        oracle_tmf_version   = "1.0.0"\n'
            f'        description          = "ORACLE-TMF proactive forecast: {mag.malware_family} '
            f'→ {forecast.predicted_technique} ({forecast.technique_name})"\n'
            f'        author               = "{STIX_IDENTITY_NAME}"\n'
            f'        date                 = "{datetime.now(timezone.utc).strftime("%Y-%m-%d")}"\n'
            f'        confidence           = "{forecast.confidence_score:.3f}"\n'
            f'        mitre_tactic         = "{forecast.predicted_tactic}"\n'
            f'        mitre_technique      = "{forecast.predicted_technique} - {forecast.technique_name}"\n'
            f'        malware_family       = "{mag.malware_family}"\n'
            f'        apk_sha256_analyzed  = "{mag.apk_metadata.sha256}"\n'
            f'        forecast_status      = "PROACTIVE_v_n_plus_1"\n'
        )
        if forecast.predicted_target_institutions:
            meta_block += f'        predicted_targets    = "{", ".join(forecast.predicted_target_institutions[:3])}"\n'

        # ── STRINGS ─────────────────────────────────────────────────────
        strings_lines: list[str] = []

        # Dead code indicators
        for i, artifact in enumerate(mag.dead_code[:3], 1):
            # Extract the most distinctive token from the method name
            token = artifact.method_name.split("(")[0][:40].strip()
            if token and len(token) > 4:
                strings_lines.append(f'        $dead_code_{i}  = "{token}" ascii nocase')

        # C2 stub indicators
        for i, stub in enumerate(mag.c2_stubs[:2], 1):
            if stub.extracted_url:
                url_token = stub.extracted_url[:60].replace('"', '\\"')
                strings_lines.append(f'        $c2_stub_{i}     = "{url_token}" ascii')
            if stub.framework:
                strings_lines.append(f'        $c2_framework_{i} = "{stub.framework}" ascii')

        # Unused permission indicators
        for i, perm in enumerate(mag.unused_permissions[:2], 1):
            pname = perm.permission_name.replace('"', '\\"')
            strings_lines.append(f'        $unused_perm_{i}  = "{pname}" ascii')

        # High-entropy placeholder strings
        for i, ps in enumerate(
            sorted(mag.placeholder_strings, key=lambda x: x.entropy, reverse=True)[:2], 1
        ):
            if ps.entropy > 4.5 and len(ps.value) < 80:
                token = ps.value[:60].replace('"', '\\"').replace("\\", "\\\\")
                strings_lines.append(f'        $placeholder_{i}  = "{token}" ascii')

        if not strings_lines:
            strings_lines.append(
                f'        $family_marker = "{mag.malware_family}" ascii nocase'
            )

        strings_block = "    strings:\n" + "\n".join(strings_lines) + "\n"

        # ── CONDITION ────────────────────────────────────────────────────
        condition_block = (
            f"    condition:\n"
            f"        uint16(0) == 0x6B50 and  // APK/ZIP magic bytes\n"
            f"        filesize < 100MB and\n"
            f"        (\n"
            f"            2 of ($dead_code_*) or\n"
            f"            (1 of ($c2_stub_*) and 1 of ($unused_perm_*))\n"
            f"        )\n"
        )

        return (
            f"rule {rule_name}\n"
            f"{{\n"
            f"{meta_block}"
            f"{strings_block}"
            f"{condition_block}"
            f"}}\n\n"
        )

    def _yara_fingerprint_rule(self, mag: MutationArtifactGraph) -> str:
        """Generic APK fingerprint rule when no forecast passes the gate."""
        import re
        family_clean = re.sub(r"\W+", "_", mag.malware_family or "UNKNOWN")
        rule_name = f"ORACLE_TMF_{family_clean}_APK_Fingerprint"

        return (
            f"rule {rule_name}\n"
            f"{{\n"
            f"    meta:\n"
            f'        description = "ORACLE-TMF APK fingerprint — no high-confidence forecast"\n'
            f'        apk_sha256  = "{mag.apk_metadata.sha256}"\n'
            f'        package     = "{mag.apk_metadata.package_name}"\n'
            f"    condition:\n"
            f'        uint16(0) == 0x6B50 and\n'
            f'        hash.sha256(0, filesize) == "{mag.apk_metadata.sha256}"\n'
            f"}}\n\n"
        )

    # ─────────────────────────────────────────────────────────
    #  OUTPUT 3 — STIX 2.1 BUNDLE
    # ─────────────────────────────────────────────────────────

    def _generate_stix(self, mag: MutationArtifactGraph, stem: str) -> str:
        """
        Generate a STIX 2.1 bundle containing:
          • Identity  — ORACLE-TMF as the intelligence producer
          • Malware   — the analysed malware family
          • Indicators — one per passing forecast (proactive detection pattern)
          • AttackPatterns — MITRE ATT&CK technique references
          • Relationships — Indicator → indicates → Malware
                           Malware → uses → AttackPattern

        The bundle is TAXII-compatible and can be submitted directly to a
        TAXII 2.1 collection endpoint.
        """
        try:
            import stix2  # type: ignore
        except ImportError:
            raise ImportError(
                "stix2 not installed. Run: pip install stix2 --break-system-packages"
            )

        now = datetime.now(timezone.utc)
        stix_objects: list = []

        # ── Identity (ORACLE-TMF system) ─────────────────────────────
        identity = stix2.Identity(
            name           = STIX_IDENTITY_NAME,
            identity_class = STIX_IDENTITY_CLASS,
            description    = (
                "ORACLE-TMF: Observational Reasoning and Coercive Analysis for "
                "Latent Evolution — Temporal Mutation Forecaster. "
                "Automated proactive threat intelligence platform."
            ),
        )
        stix_objects.append(identity)

        # ── Malware object ────────────────────────────────────────────
        family_name = mag.malware_family or mag.apk_metadata.package_name or "UnknownMalware"
        malware = stix2.Malware(
            name               = family_name,
            is_family          = True,
            malware_types      = ["banking-trojan"],
            description        = (
                f"Android banking trojan identified from APK "
                f"{mag.apk_metadata.sha256[:16]}... "
                f"Package: {mag.apk_metadata.package_name}"
            ),
            created_by_ref     = identity.id,
            first_seen         = now,
        )
        stix_objects.append(malware)

        passed = mag.high_confidence_forecasts(CONFIDENCE_GATE_THRESHOLD)
        for forecast in passed:
            # ── AttackPattern (MITRE technique) ──────────────────────
            attack_pattern = stix2.AttackPattern(
                name              = f"{forecast.predicted_technique} - {forecast.technique_name}",
                description       = (
                    f"MITRE ATT&CK for Mobile: {forecast.predicted_tactic} / "
                    f"{forecast.predicted_technique}"
                ),
                created_by_ref    = identity.id,
                external_references = [
                    stix2.ExternalReference(
                        source_name = "MITRE ATT&CK for Mobile",
                        url         = f"https://attack.mitre.org/techniques/{forecast.predicted_technique.replace('.', '/')}/",
                        external_id = forecast.predicted_technique,
                    )
                ],
            )
            stix_objects.append(attack_pattern)

            # ── Indicator (proactive YARA-style STIX pattern) ─────────
            # Use the APK hash as the indicator pattern — the STIX indicator
            # represents the artifact-laden APK that predicts v_{n+1}
            sha256_hash = mag.apk_metadata.sha256
            stix_pattern = f"[file:hashes.'SHA-256' = '{sha256_hash}']" if sha256_hash else (
                f"[software:name = '{family_name}']"
            )
            indicator = stix2.Indicator(
                name              = f"ORACLE-TMF Forecast: {forecast.predicted_technique}",
                description       = (
                    f"PROACTIVE FORECAST (confidence={forecast.confidence_score:.3f}): "
                    f"The analysed {family_name} APK contains mutation artifacts that predict "
                    f"implementation of {forecast.predicted_technique} ({forecast.technique_name}) "
                    f"in the next release. Rationale: {forecast.rationale[:400]}"
                ),
                pattern           = stix_pattern,
                pattern_type      = "stix",
                valid_from        = now,
                indicator_types   = ["malicious-activity"],
                confidence        = int(forecast.confidence_score * 100),
                created_by_ref    = identity.id,
                labels            = ["oracle-tmf-proactive-forecast"],
            )
            stix_objects.append(indicator)

            # ── Relationship: Indicator → indicates → Malware ──────────
            rel_indicates = stix2.Relationship(
                relationship_type = "indicates",
                source_ref        = indicator.id,
                target_ref        = malware.id,
                created_by_ref    = identity.id,
                description       = f"Mutation artifacts in this APK indicate future {family_name} capability",
            )
            stix_objects.append(rel_indicates)

            # ── Relationship: Malware → uses → AttackPattern ───────────
            rel_uses = stix2.Relationship(
                relationship_type = "uses",
                source_ref        = malware.id,
                target_ref        = attack_pattern.id,
                created_by_ref    = identity.id,
                description       = f"ORACLE-TMF predicts {family_name} will use this technique in v_{{n+1}}",
            )
            stix_objects.append(rel_uses)

        bundle = stix2.Bundle(objects=stix_objects, allow_custom=True)

        path = os.path.join(REPORT_OUTPUT_DIR, f"{stem}_stix_bundle.json")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(bundle.serialize(pretty=True))
        logger.debug("[Stage L] STIX 2.1 bundle written: %s (%d objects)", path, len(stix_objects))
        return path

    # ─────────────────────────────────────────────────────────
    #  OUTPUT 4 — PDF INTELLIGENCE BRIEF
    # ─────────────────────────────────────────────────────────

    def _generate_pdf(self, mag: MutationArtifactGraph, stem: str) -> str:
        """
        Generate a human-readable PDF intelligence brief for SOC analysts.

        Structure:
          Page 1  — Cover / Executive Summary
          Page 2  — APK Metadata + Artifact Inventory Table
          Page 3+ — Per-forecast detail pages (one per passing forecast)
          Final   — Appendix: Stage errors and pipeline timings
        """
        try:
            from fpdf import FPDF  # type: ignore
        except ImportError:
            raise ImportError(
                "fpdf2 not installed. Run: pip install fpdf2 --break-system-packages"
            )

        class TMFReport(FPDF):
            """Custom FPDF subclass for ORACLE-TMF branded reports."""

            BRAND_DARK   = (15,  15,  30)
            BRAND_CYAN   = (0,   245, 255)
            BRAND_GREEN  = (0,   255, 100)
            BRAND_WHITE  = (240, 240, 240)
            BRAND_GREY   = (100, 100, 120)

            def header(self):
                self.set_fill_color(*self.BRAND_DARK)
                self.rect(0, 0, 210, 14, "F")
                self.set_font("Helvetica", "B", 8)
                self.set_text_color(*self.BRAND_CYAN)
                self.set_y(4)
                self.cell(0, 6, "ORACLE-TMF  ·  PROACTIVE THREAT INTELLIGENCE BRIEF  ·  CONFIDENTIAL", align="C")
                self.ln(10)

            def footer(self):
                self.set_y(-12)
                self.set_font("Helvetica", "", 7)
                self.set_text_color(*self.BRAND_GREY)
                self.cell(0, 5, f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  ·  Page {self.page_no()}", align="C")

            def section_title(self, title: str) -> None:
                self.set_fill_color(*self.BRAND_DARK)
                self.set_text_color(*self.BRAND_CYAN)
                self.set_font("Helvetica", "B", 11)
                self.cell(0, 8, f"  {title}", fill=True, ln=True)
                self.ln(2)

            def key_value_row(self, key: str, value: str) -> None:
                self.set_font("Helvetica", "B", 9)
                self.set_text_color(*self.BRAND_GREY)
                self.cell(55, 6, key + ":", ln=False)
                self.set_font("Helvetica", "", 9)
                self.set_text_color(*self.BRAND_WHITE)
                self.multi_cell(0, 6, value[:120])

            def confidence_bar(self, score: float, label: str) -> None:
                """Draw a visual confidence bar."""
                bar_w = 130
                filled = int(bar_w * score)
                # Background
                self.set_fill_color(40, 40, 60)
                self.rect(self.get_x(), self.get_y(), bar_w, 6, "F")
                # Filled portion
                color = (0, 255, 100) if score > 0.8 else (255, 200, 0) if score > 0.6 else (255, 80, 80)
                self.set_fill_color(*color)
                self.rect(self.get_x(), self.get_y(), filled, 6, "F")
                # Label
                self.set_font("Helvetica", "B", 8)
                self.set_text_color(255, 255, 255)
                x_after = self.get_x() + bar_w + 4
                self.set_xy(x_after, self.get_y())
                self.cell(50, 6, f"{label}  ({score:.3f})")
                self.ln(8)

        pdf = TMFReport()
        pdf.set_fill_color(15, 15, 30)
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.set_margins(12, 16, 12)

        # ── PAGE 1: COVER ───────────────────────────────────────────────
        pdf.add_page()
        pdf.set_fill_color(15, 15, 30)
        pdf.rect(0, 0, 210, 297, "F")   # Dark background

        # Title
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_text_color(0, 245, 255)
        pdf.set_y(30)
        pdf.cell(0, 12, "ORACLE-TMF", align="C", ln=True)
        pdf.set_font("Helvetica", "", 13)
        pdf.set_text_color(200, 200, 220)
        pdf.cell(0, 8, "Proactive Mutation Intelligence Brief", align="C", ln=True)
        pdf.ln(4)

        # Divider
        pdf.set_draw_color(0, 245, 255)
        pdf.set_line_width(0.8)
        pdf.line(30, pdf.get_y(), 180, pdf.get_y())
        pdf.ln(6)

        # APK summary box
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(0, 245, 255)
        pdf.cell(0, 7, f"Target: {mag.malware_family or 'UNKNOWN FAMILY'}", align="C", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(180, 180, 200)
        sha_display = mag.apk_metadata.sha256[:32] + "..." if mag.apk_metadata.sha256 else "N/A"
        pdf.cell(0, 6, f"SHA256: {sha_display}", align="C", ln=True)
        pdf.cell(0, 6, f"Package: {mag.apk_metadata.package_name or 'N/A'}", align="C", ln=True)
        pdf.ln(8)

        # Forecast summary
        passed = mag.high_confidence_forecasts(CONFIDENCE_GATE_THRESHOLD)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(0, 255, 100)
        pdf.cell(0, 10, f"{len(passed)} High-Confidence Forecast(s) Generated", align="C", ln=True)
        pdf.ln(4)

        if passed:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(200, 200, 220)
            for f in passed[:3]:
                pdf.cell(0, 6, f"→  {f.predicted_technique}  ({f.technique_name})", align="C", ln=True)

        pdf.ln(8)
        # Artifact counts
        counts = mag.artifact_class_counts()
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(0, 245, 255)
        pdf.cell(0, 7, "Artifact Inventory", align="C", ln=True)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(180, 180, 200)
        for cls, count in counts.items():
            if count > 0:
                cls_display = cls.replace("CLASS_", "").replace("_", " ")
                pdf.cell(0, 5, f"  {cls_display}: {count}", align="C", ln=True)

        # ── PAGE 2: METADATA + ARTIFACT TABLE ────────────────────────────
        pdf.add_page()
        pdf.set_fill_color(15, 15, 30)
        pdf.rect(0, 0, 210, 297, "F")

        pdf.section_title("APK Metadata")
        meta = mag.apk_metadata
        fields = [
            ("SHA-256",       meta.sha256 or "N/A"),
            ("MD5",           meta.md5 or "N/A"),
            ("Package",       meta.package_name or "N/A"),
            ("Version",       f"{meta.version_name} (code {meta.version_code})"),
            ("Size",          f"{meta.file_size_bytes / 1024:.1f} KB"),
            ("Min SDK",       str(meta.min_sdk)),
            ("Target SDK",    str(meta.target_sdk)),
            ("Cert Issuer",   meta.cert_issuer[:80] or "N/A"),
            ("Packed",        "YES — " + meta.packer_hint if meta.is_packed else "No"),
            ("Family",        mag.malware_family or "Unidentified"),
            ("Family Ver.",   mag.family_version or "Unknown"),
        ]
        for k, v in fields:
            pdf.key_value_row(k, v)

        pdf.ln(6)
        pdf.section_title("7-Class Mutation Artifact Inventory")

        # Table header
        col_widths = [90, 30, 30, 36]
        headers    = ["Artifact Class", "Count", "Gate", "Risk"]
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(0, 245, 255)
        pdf.set_fill_color(20, 20, 40)
        for h, w in zip(headers, col_widths):
            pdf.cell(w, 7, h, border=1, fill=True)
        pdf.ln()

        row_data = [
            ("CLASS 1 — Dead Code / Unreachable Methods",   len(mag.dead_code),           "→ DTE",   "HIGH"),
            ("CLASS 2 — Unused Permission Intents",          len(mag.unused_permissions),  "→ Stage J","HIGH"),
            ("CLASS 3 — Placeholder Strings & Resources",    len(mag.placeholder_strings), "→ Stage J","MEDIUM"),
            ("CLASS 4 — C2 Endpoint Stubs",                  len(mag.c2_stubs),            "→ Stage J","CRITICAL"),
            ("CLASS 5 — Partial API Implementations",        len(mag.partial_apis),        "→ DTE",   "HIGH"),
            ("CLASS 6 — Unfinished UI Flows",                len(mag.unfinished_ui_flows), "→ Stage J","MEDIUM"),
            ("CLASS 7 — GenAI API Scaffolds (TMF-Psi)",     len(mag.genai_scaffolds),     "→ Stage J","CRITICAL"),
        ]
        pdf.set_font("Helvetica", "", 8)
        for row in row_data:
            cls_name, count, gate, risk = row
            risk_colors = {"CRITICAL": (255, 60, 60), "HIGH": (255, 160, 0), "MEDIUM": (200, 200, 0)}
            pdf.set_text_color(200, 200, 220)
            pdf.cell(col_widths[0], 6, cls_name[:55], border=1)
            pdf.cell(col_widths[1], 6, str(count), border=1, align="C")
            pdf.cell(col_widths[2], 6, gate, border=1, align="C")
            pdf.set_text_color(*risk_colors.get(risk, (200, 200, 200)))
            pdf.cell(col_widths[3], 6, risk, border=1, align="C")
            pdf.ln()
            pdf.set_text_color(200, 200, 220)

        # ── PAGE 3+: PER-FORECAST DETAIL ─────────────────────────────────
        for i, forecast in enumerate(passed, 1):
            pdf.add_page()
            pdf.set_fill_color(15, 15, 30)
            pdf.rect(0, 0, 210, 297, "F")

            pdf.section_title(f"Forecast #{i}: {forecast.predicted_technique}")

            # Confidence bar
            pdf.set_text_color(0, 245, 255)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, "Bayesian Confidence Score", ln=True)
            pdf.confidence_bar(forecast.confidence_score, "C")
            pdf.ln(2)

            # Technique details
            pdf.key_value_row("MITRE Tactic",      forecast.predicted_tactic)
            pdf.key_value_row("MITRE Technique",    f"{forecast.predicted_technique} — {forecast.technique_name}")
            pdf.key_value_row("P_LLM",              f"{forecast.p_llm:.3f}  (Skeptical Validator)")
            pdf.key_value_row("D_artifact × MVV",   f"{forecast.artifact_density:.3f} × {forecast.mvv_normalized:.3f} = {forecast.artifact_density * forecast.mvv_normalized:.3f}")
            pdf.key_value_row("H_prior",             f"{forecast.h_prior:.3f}  (Historical family frequency)")
            pdf.ln(3)

            # Supporting artifacts
            pdf.section_title("Supporting Artifact Classes")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(180, 200, 180)
            for cls in forecast.supporting_artifacts:
                pdf.cell(0, 6, f"  ✓  {cls}", ln=True)
            pdf.ln(3)

            # Targeting intelligence
            if forecast.predicted_target_institutions:
                pdf.section_title("Targeting Intelligence")
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(255, 160, 0)
                pdf.cell(0, 6, "Predicted Target Institutions:", ln=True)
                pdf.set_text_color(200, 200, 220)
                for inst in forecast.predicted_target_institutions:
                    pdf.cell(0, 5, f"  → {inst}", ln=True)
                if forecast.predicted_target_countries:
                    pdf.set_text_color(255, 160, 0)
                    pdf.cell(0, 6, "Predicted Target Regions:", ln=True)
                    pdf.set_text_color(200, 200, 220)
                    for country in forecast.predicted_target_countries:
                        pdf.cell(0, 5, f"  → {country}", ln=True)
                pdf.ln(3)

            # Rationale (wrapped text)
            pdf.section_title("Analyst Rationale (LLM Chain-of-Thought)")
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(190, 190, 210)
            wrapped = textwrap.fill(forecast.rationale[:800], width=100)
            for line in wrapped.splitlines():
                pdf.cell(0, 5, line[:100], ln=True)

        # ── APPENDIX: PIPELINE HEALTH ─────────────────────────────────────
        if mag.stage_errors or mag.stage_timings_ms:
            pdf.add_page()
            pdf.set_fill_color(15, 15, 30)
            pdf.rect(0, 0, 210, 297, "F")

            pdf.section_title("Appendix — Pipeline Diagnostics")
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(0, 245, 255)
            pdf.cell(0, 7, "Stage Timings", ln=True)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(180, 180, 200)
            for stage, ms in sorted(mag.stage_timings_ms.items()):
                pdf.cell(0, 5, f"  {stage:<20}  {ms:.1f} ms", ln=True)

            if mag.stage_errors:
                pdf.ln(4)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(255, 80, 80)
                pdf.cell(0, 7, "Stage Errors", ln=True)
                pdf.set_font("Helvetica", "", 8)
                for stage, err in mag.stage_errors.items():
                    pdf.cell(0, 5, f"  {stage}: {str(err)[:80]}", ln=True)

        path = os.path.join(REPORT_OUTPUT_DIR, f"{stem}_intelligence_brief.pdf")
        pdf.output(path)
        logger.debug("[Stage L] PDF brief written: %s (%d pages)", path, pdf.page)
        return path

    # ─────────────────────────────────────────────────────────
    #  INTERNAL UTILITIES
    # ─────────────────────────────────────────────────────────

    def _safe_generate(self, format_name: str, bundle: ReportBundle, generator_fn) -> str:
        """
        Execute a report generator function, capturing any exception into
        bundle.errors rather than propagating it.  Returns the output path
        or empty string on failure.
        """
        try:
            return generator_fn()
        except Exception as exc:
            logger.warning("[Stage L] %s generation failed: %s", format_name.upper(), exc)
            bundle.errors[format_name] = str(exc)
            return ""

    @staticmethod
    def _report_stem(mag: MutationArtifactGraph) -> str:
        """Generate a filesystem-safe stem for report file names."""
        import re
        sha_prefix  = mag.apk_metadata.sha256[:12] if mag.apk_metadata.sha256 else "unknown"
        family_part = re.sub(r"\W+", "_", mag.malware_family or "unknown")
        ts          = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        return f"{family_part}_{sha_prefix}_{ts}"
